/*
 * generated by Xtext
 */
package org.chor.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class ChorUiModule extends org.chor.ui.AbstractChorUiModule {
	public ChorUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
