/*
 * generated by Xtext
 */
package org.chor;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class ChorRuntimeModule extends org.chor.AbstractChorRuntimeModule {

}
