/*
* generated by Xtext
*/
package org.chor.parser.antlr;

import com.google.inject.Inject;

import org.eclipse.xtext.parser.antlr.XtextTokenStream;
import org.chor.services.ChorGrammarAccess;

public class ChorParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject
	private ChorGrammarAccess grammarAccess;
	
	@Override
	protected void setInitialHiddenTokens(XtextTokenStream tokenStream) {
		tokenStream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
	}
	
	@Override
	protected org.chor.parser.antlr.internal.InternalChorParser createParser(XtextTokenStream stream) {
		return new org.chor.parser.antlr.internal.InternalChorParser(stream, getGrammarAccess());
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Program";
	}
	
	public ChorGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(ChorGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
	
}
