/*
* generated by Xtext
*/

package org.chor.services;

import com.google.inject.Singleton;
import com.google.inject.Inject;

import org.eclipse.xtext.*;
import org.eclipse.xtext.service.GrammarProvider;
import org.eclipse.xtext.service.AbstractElementFinder.*;

import org.eclipse.xtext.common.services.TerminalsGrammarAccess;

@Singleton
public class ChorGrammarAccess extends AbstractGrammarElementFinder {
	
	
	public class ProgramElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Program");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProgramKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cSEMICOLONTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cPreambleAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cPreamblePreambleParserRuleCall_3_0 = (RuleCall)cPreambleAssignment_3.eContents().get(0);
		private final Keyword cMainKeyword_4 = (Keyword)cGroup.eContents().get(4);
		private final RuleCall cLCURLYTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cChoreographyAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cChoreographyChoreographyParserRuleCall_6_0 = (RuleCall)cChoreographyAssignment_6.eContents().get(0);
		private final RuleCall cRCURLYTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		
		//// Main nonterminal
		//Program:
		//	"program" name=ID SEMICOLON preamble=Preamble "main" LCURLY choreography=Choreography RCURLY;
		public ParserRule getRule() { return rule; }

		//"program" name=ID SEMICOLON preamble=Preamble "main" LCURLY choreography=Choreography RCURLY
		public Group getGroup() { return cGroup; }

		//"program"
		public Keyword getProgramKeyword_0() { return cProgramKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_2() { return cSEMICOLONTerminalRuleCall_2; }

		//preamble=Preamble
		public Assignment getPreambleAssignment_3() { return cPreambleAssignment_3; }

		//Preamble
		public RuleCall getPreamblePreambleParserRuleCall_3_0() { return cPreamblePreambleParserRuleCall_3_0; }

		//"main"
		public Keyword getMainKeyword_4() { return cMainKeyword_4; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_5() { return cLCURLYTerminalRuleCall_5; }

		//choreography=Choreography
		public Assignment getChoreographyAssignment_6() { return cChoreographyAssignment_6; }

		//Choreography
		public RuleCall getChoreographyChoreographyParserRuleCall_6_0() { return cChoreographyChoreographyParserRuleCall_6_0; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_7() { return cRCURLYTerminalRuleCall_7; }
	}

	public class PreambleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Preamble");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Action cPreambleAction_0 = (Action)cGroup.eContents().get(0);
		private final Alternatives cAlternatives_1 = (Alternatives)cGroup.eContents().get(1);
		private final Assignment cProtocolsAssignment_1_0 = (Assignment)cAlternatives_1.eContents().get(0);
		private final RuleCall cProtocolsProtocolParserRuleCall_1_0_0 = (RuleCall)cProtocolsAssignment_1_0.eContents().get(0);
		private final Assignment cSiteAssignment_1_1 = (Assignment)cAlternatives_1.eContents().get(1);
		private final RuleCall cSiteSiteParserRuleCall_1_1_0 = (RuleCall)cSiteAssignment_1_1.eContents().get(0);
		
		//// Preamble of a program
		//Preamble:
		//	{Preamble} (protocols+=Protocol // Protocol definitions
		//	// Site definitions
		//	| site+=Site)*;
		public ParserRule getRule() { return rule; }

		//{Preamble} (protocols+=Protocol // Protocol definitions
		//// Site definitions
		//| site+=Site)*
		public Group getGroup() { return cGroup; }

		//{Preamble}
		public Action getPreambleAction_0() { return cPreambleAction_0; }

		//(protocols+=Protocol // Protocol definitions
		//// Site definitions
		//| site+=Site)*
		public Alternatives getAlternatives_1() { return cAlternatives_1; }

		//protocols+=Protocol
		public Assignment getProtocolsAssignment_1_0() { return cProtocolsAssignment_1_0; }

		//Protocol
		public RuleCall getProtocolsProtocolParserRuleCall_1_0_0() { return cProtocolsProtocolParserRuleCall_1_0_0; }

		//site+=Site
		public Assignment getSiteAssignment_1_1() { return cSiteAssignment_1_1; }

		//Site
		public RuleCall getSiteSiteParserRuleCall_1_1_0() { return cSiteSiteParserRuleCall_1_1_0; }
	}

	public class ProtocolElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Protocol");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cProtocolKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cLCURLYTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cTypeAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cTypeGlobalTypeParserRuleCall_3_0 = (RuleCall)cTypeAssignment_3.eContents().get(0);
		private final RuleCall cRCURLYTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		
		//// Definition of a protocol, associating a name to a multiparty behavioural type.
		//Protocol:
		//	"protocol" name=ID LCURLY type=GlobalType RCURLY;
		public ParserRule getRule() { return rule; }

		//"protocol" name=ID LCURLY type=GlobalType RCURLY
		public Group getGroup() { return cGroup; }

		//"protocol"
		public Keyword getProtocolKeyword_0() { return cProtocolKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_2() { return cLCURLYTerminalRuleCall_2; }

		//type=GlobalType
		public Assignment getTypeAssignment_3() { return cTypeAssignment_3; }

		//GlobalType
		public RuleCall getTypeGlobalTypeParserRuleCall_3_0() { return cTypeGlobalTypeParserRuleCall_3_0; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_4() { return cRCURLYTerminalRuleCall_4; }
	}

	public class SiteElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Site");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cSiteKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cNameIDTerminalRuleCall_1_0 = (RuleCall)cNameAssignment_1.eContents().get(0);
		private final RuleCall cCOLONTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cProtocolAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final CrossReference cProtocolProtocolCrossReference_3_0 = (CrossReference)cProtocolAssignment_3.eContents().get(0);
		private final RuleCall cProtocolProtocolIDTerminalRuleCall_3_0_1 = (RuleCall)cProtocolProtocolCrossReference_3_0.eContents().get(1);
		
		//// Definition of a site, associating a public channel name to a protocol.
		//Site:
		//	"site" name=ID COLON protocol=[Protocol];
		public ParserRule getRule() { return rule; }

		//"site" name=ID COLON protocol=[Protocol]
		public Group getGroup() { return cGroup; }

		//"site"
		public Keyword getSiteKeyword_0() { return cSiteKeyword_0; }

		//name=ID
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//ID
		public RuleCall getNameIDTerminalRuleCall_1_0() { return cNameIDTerminalRuleCall_1_0; }

		//COLON
		public RuleCall getCOLONTerminalRuleCall_2() { return cCOLONTerminalRuleCall_2; }

		//protocol=[Protocol]
		public Assignment getProtocolAssignment_3() { return cProtocolAssignment_3; }

		//[Protocol]
		public CrossReference getProtocolProtocolCrossReference_3_0() { return cProtocolProtocolCrossReference_3_0; }

		//ID
		public RuleCall getProtocolProtocolIDTerminalRuleCall_3_0_1() { return cProtocolProtocolIDTerminalRuleCall_3_0_1; }
	}

	public class GlobalTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "GlobalType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSenderAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSenderIDTerminalRuleCall_0_0 = (RuleCall)cSenderAssignment_0.eContents().get(0);
		private final RuleCall cARROWTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cReceiverAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cReceiverIDTerminalRuleCall_2_0 = (RuleCall)cReceiverAssignment_2.eContents().get(0);
		private final RuleCall cCOLONTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Alternatives cAlternatives_4 = (Alternatives)cGroup.eContents().get(4);
		private final Assignment cBranchesAssignment_4_0 = (Assignment)cAlternatives_4.eContents().get(0);
		private final RuleCall cBranchesBranchGTypeParserRuleCall_4_0_0 = (RuleCall)cBranchesAssignment_4_0.eContents().get(0);
		private final Group cGroup_4_1 = (Group)cAlternatives_4.eContents().get(1);
		private final RuleCall cLCURLYTerminalRuleCall_4_1_0 = (RuleCall)cGroup_4_1.eContents().get(0);
		private final Assignment cBranchesAssignment_4_1_1 = (Assignment)cGroup_4_1.eContents().get(1);
		private final RuleCall cBranchesBranchGTypeParserRuleCall_4_1_1_0 = (RuleCall)cBranchesAssignment_4_1_1.eContents().get(0);
		private final Group cGroup_4_1_2 = (Group)cGroup_4_1.eContents().get(2);
		private final RuleCall cCOMMATerminalRuleCall_4_1_2_0 = (RuleCall)cGroup_4_1_2.eContents().get(0);
		private final Assignment cBranchesAssignment_4_1_2_1 = (Assignment)cGroup_4_1_2.eContents().get(1);
		private final RuleCall cBranchesBranchGTypeParserRuleCall_4_1_2_1_0 = (RuleCall)cBranchesAssignment_4_1_2_1.eContents().get(0);
		private final RuleCall cRCURLYTerminalRuleCall_4_1_3 = (RuleCall)cGroup_4_1.eContents().get(3);
		
		//// Multiparty behavioural type, also denoted with G in comments for brevity (referring to the theoretical papers).
		//GlobalType: // Interaction. Example: A -> B: op(string); G
		//	sender=ID ARROW receiver=ID COLON (branches+=BranchGType | LCURLY branches+=BranchGType (COMMA branches+=BranchGType)*
		//	RCURLY);
		public ParserRule getRule() { return rule; }

		//// Interaction. Example: A -> B: op(string); G
		//sender=ID ARROW receiver=ID COLON (branches+=BranchGType | LCURLY branches+=BranchGType (COMMA branches+=BranchGType)*
		//RCURLY)
		public Group getGroup() { return cGroup; }

		//// Interaction. Example: A -> B: op(string); G
		//sender=ID
		public Assignment getSenderAssignment_0() { return cSenderAssignment_0; }

		//ID
		public RuleCall getSenderIDTerminalRuleCall_0_0() { return cSenderIDTerminalRuleCall_0_0; }

		//ARROW
		public RuleCall getARROWTerminalRuleCall_1() { return cARROWTerminalRuleCall_1; }

		//receiver=ID
		public Assignment getReceiverAssignment_2() { return cReceiverAssignment_2; }

		//ID
		public RuleCall getReceiverIDTerminalRuleCall_2_0() { return cReceiverIDTerminalRuleCall_2_0; }

		//COLON
		public RuleCall getCOLONTerminalRuleCall_3() { return cCOLONTerminalRuleCall_3; }

		//branches+=BranchGType | LCURLY branches+=BranchGType (COMMA branches+=BranchGType)* RCURLY
		public Alternatives getAlternatives_4() { return cAlternatives_4; }

		//branches+=BranchGType
		public Assignment getBranchesAssignment_4_0() { return cBranchesAssignment_4_0; }

		//BranchGType
		public RuleCall getBranchesBranchGTypeParserRuleCall_4_0_0() { return cBranchesBranchGTypeParserRuleCall_4_0_0; }

		//LCURLY branches+=BranchGType (COMMA branches+=BranchGType)* RCURLY
		public Group getGroup_4_1() { return cGroup_4_1; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_4_1_0() { return cLCURLYTerminalRuleCall_4_1_0; }

		//branches+=BranchGType
		public Assignment getBranchesAssignment_4_1_1() { return cBranchesAssignment_4_1_1; }

		//BranchGType
		public RuleCall getBranchesBranchGTypeParserRuleCall_4_1_1_0() { return cBranchesBranchGTypeParserRuleCall_4_1_1_0; }

		//(COMMA branches+=BranchGType)*
		public Group getGroup_4_1_2() { return cGroup_4_1_2; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_4_1_2_0() { return cCOMMATerminalRuleCall_4_1_2_0; }

		//branches+=BranchGType
		public Assignment getBranchesAssignment_4_1_2_1() { return cBranchesAssignment_4_1_2_1; }

		//BranchGType
		public RuleCall getBranchesBranchGTypeParserRuleCall_4_1_2_1_0() { return cBranchesBranchGTypeParserRuleCall_4_1_2_1_0; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_4_1_3() { return cRCURLYTerminalRuleCall_4_1_3; }
	}

	public class BranchGTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BranchGType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cOperationAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cOperationIDTerminalRuleCall_0_0 = (RuleCall)cOperationAssignment_0.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cDataTypeAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cDataTypeDataTypeParserRuleCall_2_0 = (RuleCall)cDataTypeAssignment_2.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final RuleCall cSEMICOLONTerminalRuleCall_4_0 = (RuleCall)cGroup_4.eContents().get(0);
		private final Assignment cContinuationAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cContinuationGlobalTypeParserRuleCall_4_1_0 = (RuleCall)cContinuationAssignment_4_1.eContents().get(0);
		
		//// Type of a branch. Example: label: G
		//BranchGType:
		//	operation=ID LPAREN dataType=DataType RPAREN (SEMICOLON continuation=GlobalType)?;
		public ParserRule getRule() { return rule; }

		//operation=ID LPAREN dataType=DataType RPAREN (SEMICOLON continuation=GlobalType)?
		public Group getGroup() { return cGroup; }

		//operation=ID
		public Assignment getOperationAssignment_0() { return cOperationAssignment_0; }

		//ID
		public RuleCall getOperationIDTerminalRuleCall_0_0() { return cOperationIDTerminalRuleCall_0_0; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1() { return cLPARENTerminalRuleCall_1; }

		//dataType=DataType
		public Assignment getDataTypeAssignment_2() { return cDataTypeAssignment_2; }

		//DataType
		public RuleCall getDataTypeDataTypeParserRuleCall_2_0() { return cDataTypeDataTypeParserRuleCall_2_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_3() { return cRPARENTerminalRuleCall_3; }

		//(SEMICOLON continuation=GlobalType)?
		public Group getGroup_4() { return cGroup_4; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_4_0() { return cSEMICOLONTerminalRuleCall_4_0; }

		//continuation=GlobalType
		public Assignment getContinuationAssignment_4_1() { return cContinuationAssignment_4_1; }

		//GlobalType
		public RuleCall getContinuationGlobalTypeParserRuleCall_4_1_0() { return cContinuationGlobalTypeParserRuleCall_4_1_0; }
	}

	public class DataTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "DataType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cBasicTypeParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cLocalTypeParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		
		//// Data types. 
		//DataType:
		//	BasicType | LocalType;
		public ParserRule getRule() { return rule; }

		//BasicType | LocalType
		public Alternatives getAlternatives() { return cAlternatives; }

		//BasicType
		public RuleCall getBasicTypeParserRuleCall_0() { return cBasicTypeParserRuleCall_0; }

		//LocalType
		public RuleCall getLocalTypeParserRuleCall_1() { return cLocalTypeParserRuleCall_1; }
	}

	public class BasicTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BasicType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cBasicTypeAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final Assignment cNameAssignment_0_1 = (Assignment)cGroup_0.eContents().get(1);
		private final Keyword cNameIntKeyword_0_1_0 = (Keyword)cNameAssignment_0_1.eContents().get(0);
		private final Assignment cNameAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final Keyword cNameStringKeyword_1_0 = (Keyword)cNameAssignment_1.eContents().get(0);
		private final Assignment cNameAssignment_2 = (Assignment)cAlternatives.eContents().get(2);
		private final Keyword cNameBoolKeyword_2_0 = (Keyword)cNameAssignment_2.eContents().get(0);
		private final Assignment cNameAssignment_3 = (Assignment)cAlternatives.eContents().get(3);
		private final Keyword cNameVoidKeyword_3_0 = (Keyword)cNameAssignment_3.eContents().get(0);
		
		//// Basic types. Example: int
		//BasicType:
		//	{BasicType} name="int" | name="string" | name="bool" | name="void";
		public ParserRule getRule() { return rule; }

		//{BasicType} name="int" | name="string" | name="bool" | name="void"
		public Alternatives getAlternatives() { return cAlternatives; }

		//{BasicType} name="int"
		public Group getGroup_0() { return cGroup_0; }

		//{BasicType}
		public Action getBasicTypeAction_0_0() { return cBasicTypeAction_0_0; }

		//name="int"
		public Assignment getNameAssignment_0_1() { return cNameAssignment_0_1; }

		//"int"
		public Keyword getNameIntKeyword_0_1_0() { return cNameIntKeyword_0_1_0; }

		//name="string"
		public Assignment getNameAssignment_1() { return cNameAssignment_1; }

		//"string"
		public Keyword getNameStringKeyword_1_0() { return cNameStringKeyword_1_0; }

		//name="bool"
		public Assignment getNameAssignment_2() { return cNameAssignment_2; }

		//"bool"
		public Keyword getNameBoolKeyword_2_0() { return cNameBoolKeyword_2_0; }

		//name="void"
		public Assignment getNameAssignment_3() { return cNameAssignment_3; }

		//"void"
		public Keyword getNameVoidKeyword_3_0() { return cNameVoidKeyword_3_0; }
	}

	public class LocalTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "LocalType");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cOutputTypeAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final RuleCall cBANGTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final RuleCall cLPARENTerminalRuleCall_0_2 = (RuleCall)cGroup_0.eContents().get(2);
		private final Assignment cDatatypeAssignment_0_3 = (Assignment)cGroup_0.eContents().get(3);
		private final RuleCall cDatatypeDataTypeParserRuleCall_0_3_0 = (RuleCall)cDatatypeAssignment_0_3.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_0_4 = (RuleCall)cGroup_0.eContents().get(4);
		private final RuleCall cSEMICOLONTerminalRuleCall_0_5 = (RuleCall)cGroup_0.eContents().get(5);
		private final Assignment cContinuationAssignment_0_6 = (Assignment)cGroup_0.eContents().get(6);
		private final RuleCall cContinuationLocalTypeParserRuleCall_0_6_0 = (RuleCall)cContinuationAssignment_0_6.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cInputTypeAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cQUESTION_MARKTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final RuleCall cLPARENTerminalRuleCall_1_2 = (RuleCall)cGroup_1.eContents().get(2);
		private final Assignment cDatatypeAssignment_1_3 = (Assignment)cGroup_1.eContents().get(3);
		private final RuleCall cDatatypeDataTypeParserRuleCall_1_3_0 = (RuleCall)cDatatypeAssignment_1_3.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_1_4 = (RuleCall)cGroup_1.eContents().get(4);
		private final RuleCall cSEMICOLONTerminalRuleCall_1_5 = (RuleCall)cGroup_1.eContents().get(5);
		private final Assignment cContinuationAssignment_1_6 = (Assignment)cGroup_1.eContents().get(6);
		private final RuleCall cContinuationLocalTypeParserRuleCall_1_6_0 = (RuleCall)cContinuationAssignment_1_6.eContents().get(0);
		private final Group cGroup_2 = (Group)cAlternatives.eContents().get(2);
		private final Action cBranchingTypeAction_2_0 = (Action)cGroup_2.eContents().get(0);
		private final RuleCall cQUESTION_MARKTerminalRuleCall_2_1 = (RuleCall)cGroup_2.eContents().get(1);
		private final RuleCall cLCURLYTerminalRuleCall_2_2 = (RuleCall)cGroup_2.eContents().get(2);
		private final Assignment cBranchesAssignment_2_3 = (Assignment)cGroup_2.eContents().get(3);
		private final RuleCall cBranchesBranchTypeParserRuleCall_2_3_0 = (RuleCall)cBranchesAssignment_2_3.eContents().get(0);
		private final Group cGroup_2_4 = (Group)cGroup_2.eContents().get(4);
		private final RuleCall cCOMMATerminalRuleCall_2_4_0 = (RuleCall)cGroup_2_4.eContents().get(0);
		private final Assignment cBranchesAssignment_2_4_1 = (Assignment)cGroup_2_4.eContents().get(1);
		private final RuleCall cBranchesBranchTypeParserRuleCall_2_4_1_0 = (RuleCall)cBranchesAssignment_2_4_1.eContents().get(0);
		private final RuleCall cRCURLYTerminalRuleCall_2_5 = (RuleCall)cGroup_2.eContents().get(5);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final Action cSelectionTypeAction_3_0 = (Action)cGroup_3.eContents().get(0);
		private final RuleCall cBANGTerminalRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final RuleCall cLCURLYTerminalRuleCall_3_2 = (RuleCall)cGroup_3.eContents().get(2);
		private final Assignment cBranchesAssignment_3_3 = (Assignment)cGroup_3.eContents().get(3);
		private final RuleCall cBranchesBranchTypeParserRuleCall_3_3_0 = (RuleCall)cBranchesAssignment_3_3.eContents().get(0);
		private final Group cGroup_3_4 = (Group)cGroup_3.eContents().get(4);
		private final RuleCall cCOMMATerminalRuleCall_3_4_0 = (RuleCall)cGroup_3_4.eContents().get(0);
		private final Assignment cBranchesAssignment_3_4_1 = (Assignment)cGroup_3_4.eContents().get(1);
		private final RuleCall cBranchesBranchTypeParserRuleCall_3_4_1_0 = (RuleCall)cBranchesAssignment_3_4_1.eContents().get(0);
		private final RuleCall cRCURLYTerminalRuleCall_3_5 = (RuleCall)cGroup_3.eContents().get(5);
		
		//// Local types. 
		////	|
		//// End
		////	{EndType} 'end'
		//LocalType:
		//	{OutputType} BANG LPAREN datatype=DataType RPAREN SEMICOLON continuation=LocalType | {InputType} QUESTION_MARK LPAREN
		//	datatype=DataType RPAREN SEMICOLON continuation=LocalType | {BranchingType} QUESTION_MARK LCURLY branches+=BranchType
		//	(COMMA branches+=BranchType)* RCURLY | {SelectionType} BANG LCURLY branches+=BranchType (COMMA branches+=BranchType)*
		//	RCURLY;
		public ParserRule getRule() { return rule; }

		//{OutputType} BANG LPAREN datatype=DataType RPAREN SEMICOLON continuation=LocalType | {InputType} QUESTION_MARK LPAREN
		//datatype=DataType RPAREN SEMICOLON continuation=LocalType | {BranchingType} QUESTION_MARK LCURLY branches+=BranchType
		//(COMMA branches+=BranchType)* RCURLY | {SelectionType} BANG LCURLY branches+=BranchType (COMMA branches+=BranchType)*
		//RCURLY
		public Alternatives getAlternatives() { return cAlternatives; }

		//{OutputType} BANG LPAREN datatype=DataType RPAREN SEMICOLON continuation=LocalType
		public Group getGroup_0() { return cGroup_0; }

		//{OutputType}
		public Action getOutputTypeAction_0_0() { return cOutputTypeAction_0_0; }

		//BANG
		public RuleCall getBANGTerminalRuleCall_0_1() { return cBANGTerminalRuleCall_0_1; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_0_2() { return cLPARENTerminalRuleCall_0_2; }

		//datatype=DataType
		public Assignment getDatatypeAssignment_0_3() { return cDatatypeAssignment_0_3; }

		//DataType
		public RuleCall getDatatypeDataTypeParserRuleCall_0_3_0() { return cDatatypeDataTypeParserRuleCall_0_3_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_0_4() { return cRPARENTerminalRuleCall_0_4; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_0_5() { return cSEMICOLONTerminalRuleCall_0_5; }

		//continuation=LocalType
		public Assignment getContinuationAssignment_0_6() { return cContinuationAssignment_0_6; }

		//LocalType
		public RuleCall getContinuationLocalTypeParserRuleCall_0_6_0() { return cContinuationLocalTypeParserRuleCall_0_6_0; }

		//{InputType} QUESTION_MARK LPAREN datatype=DataType RPAREN SEMICOLON continuation=LocalType
		public Group getGroup_1() { return cGroup_1; }

		//{InputType}
		public Action getInputTypeAction_1_0() { return cInputTypeAction_1_0; }

		//QUESTION_MARK
		public RuleCall getQUESTION_MARKTerminalRuleCall_1_1() { return cQUESTION_MARKTerminalRuleCall_1_1; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1_2() { return cLPARENTerminalRuleCall_1_2; }

		//datatype=DataType
		public Assignment getDatatypeAssignment_1_3() { return cDatatypeAssignment_1_3; }

		//DataType
		public RuleCall getDatatypeDataTypeParserRuleCall_1_3_0() { return cDatatypeDataTypeParserRuleCall_1_3_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_1_4() { return cRPARENTerminalRuleCall_1_4; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_1_5() { return cSEMICOLONTerminalRuleCall_1_5; }

		//continuation=LocalType
		public Assignment getContinuationAssignment_1_6() { return cContinuationAssignment_1_6; }

		//LocalType
		public RuleCall getContinuationLocalTypeParserRuleCall_1_6_0() { return cContinuationLocalTypeParserRuleCall_1_6_0; }

		//{BranchingType} QUESTION_MARK LCURLY branches+=BranchType (COMMA branches+=BranchType)* RCURLY
		public Group getGroup_2() { return cGroup_2; }

		//{BranchingType}
		public Action getBranchingTypeAction_2_0() { return cBranchingTypeAction_2_0; }

		//QUESTION_MARK
		public RuleCall getQUESTION_MARKTerminalRuleCall_2_1() { return cQUESTION_MARKTerminalRuleCall_2_1; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_2_2() { return cLCURLYTerminalRuleCall_2_2; }

		//branches+=BranchType
		public Assignment getBranchesAssignment_2_3() { return cBranchesAssignment_2_3; }

		//BranchType
		public RuleCall getBranchesBranchTypeParserRuleCall_2_3_0() { return cBranchesBranchTypeParserRuleCall_2_3_0; }

		//(COMMA branches+=BranchType)*
		public Group getGroup_2_4() { return cGroup_2_4; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_2_4_0() { return cCOMMATerminalRuleCall_2_4_0; }

		//branches+=BranchType
		public Assignment getBranchesAssignment_2_4_1() { return cBranchesAssignment_2_4_1; }

		//BranchType
		public RuleCall getBranchesBranchTypeParserRuleCall_2_4_1_0() { return cBranchesBranchTypeParserRuleCall_2_4_1_0; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_2_5() { return cRCURLYTerminalRuleCall_2_5; }

		//{SelectionType} BANG LCURLY branches+=BranchType (COMMA branches+=BranchType)* RCURLY
		public Group getGroup_3() { return cGroup_3; }

		//{SelectionType}
		public Action getSelectionTypeAction_3_0() { return cSelectionTypeAction_3_0; }

		//BANG
		public RuleCall getBANGTerminalRuleCall_3_1() { return cBANGTerminalRuleCall_3_1; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_3_2() { return cLCURLYTerminalRuleCall_3_2; }

		//branches+=BranchType
		public Assignment getBranchesAssignment_3_3() { return cBranchesAssignment_3_3; }

		//BranchType
		public RuleCall getBranchesBranchTypeParserRuleCall_3_3_0() { return cBranchesBranchTypeParserRuleCall_3_3_0; }

		//(COMMA branches+=BranchType)*
		public Group getGroup_3_4() { return cGroup_3_4; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_3_4_0() { return cCOMMATerminalRuleCall_3_4_0; }

		//branches+=BranchType
		public Assignment getBranchesAssignment_3_4_1() { return cBranchesAssignment_3_4_1; }

		//BranchType
		public RuleCall getBranchesBranchTypeParserRuleCall_3_4_1_0() { return cBranchesBranchTypeParserRuleCall_3_4_1_0; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_3_5() { return cRCURLYTerminalRuleCall_3_5; }
	}

	public class BranchTypeElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "BranchType");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLabelAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLabelIDTerminalRuleCall_0_0 = (RuleCall)cLabelAssignment_0.eContents().get(0);
		private final RuleCall cCOLONTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final RuleCall cLocalTypeParserRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		
		//// Type of a branch. Example: label: L
		//BranchType:
		//	label=ID COLON LocalType;
		public ParserRule getRule() { return rule; }

		//label=ID COLON LocalType
		public Group getGroup() { return cGroup; }

		//label=ID
		public Assignment getLabelAssignment_0() { return cLabelAssignment_0; }

		//ID
		public RuleCall getLabelIDTerminalRuleCall_0_0() { return cLabelIDTerminalRuleCall_0_0; }

		//COLON
		public RuleCall getCOLONTerminalRuleCall_1() { return cCOLONTerminalRuleCall_1; }

		//LocalType
		public RuleCall getLocalTypeParserRuleCall_2() { return cLocalTypeParserRuleCall_2; }
	}

	public class ChoreographyElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Choreography");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cStartParserRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cInteractionParserRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cIfThenElseParserRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final Group cGroup_3 = (Group)cAlternatives.eContents().get(3);
		private final RuleCall cLCURLYTerminalRuleCall_3_0 = (RuleCall)cGroup_3.eContents().get(0);
		private final RuleCall cChoreographyParserRuleCall_3_1 = (RuleCall)cGroup_3.eContents().get(1);
		private final RuleCall cRCURLYTerminalRuleCall_3_2 = (RuleCall)cGroup_3.eContents().get(2);
		
		/// **
		// * A choreography.
		// * TODO: introduce recursion
		// * / // | End
		//Choreography:
		//	Start | Interaction | IfThenElse | LCURLY Choreography RCURLY;
		public ParserRule getRule() { return rule; }

		//Start | Interaction | IfThenElse | LCURLY Choreography RCURLY
		public Alternatives getAlternatives() { return cAlternatives; }

		//Start
		public RuleCall getStartParserRuleCall_0() { return cStartParserRuleCall_0; }

		//Interaction
		public RuleCall getInteractionParserRuleCall_1() { return cInteractionParserRuleCall_1; }

		//IfThenElse
		public RuleCall getIfThenElseParserRuleCall_2() { return cIfThenElseParserRuleCall_2; }

		//LCURLY Choreography RCURLY
		public Group getGroup_3() { return cGroup_3; }

		//LCURLY
		public RuleCall getLCURLYTerminalRuleCall_3_0() { return cLCURLYTerminalRuleCall_3_0; }

		//Choreography
		public RuleCall getChoreographyParserRuleCall_3_1() { return cChoreographyParserRuleCall_3_1; }

		//RCURLY
		public RuleCall getRCURLYTerminalRuleCall_3_2() { return cRCURLYTerminalRuleCall_3_2; }
	}

	public class StartElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Start");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cActiveThreadsAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cActiveThreadsThreadWithRoleParserRuleCall_0_0 = (RuleCall)cActiveThreadsAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cCOMMATerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final Assignment cActiveThreadsAssignment_1_1 = (Assignment)cGroup_1.eContents().get(1);
		private final RuleCall cActiveThreadsThreadWithRoleParserRuleCall_1_1_0 = (RuleCall)cActiveThreadsAssignment_1_1.eContents().get(0);
		private final Keyword cStartKeyword_2 = (Keyword)cGroup.eContents().get(2);
		private final Assignment cServiceThreadsAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cServiceThreadsThreadWithRoleParserRuleCall_3_0 = (RuleCall)cServiceThreadsAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final RuleCall cCOMMATerminalRuleCall_4_0 = (RuleCall)cGroup_4.eContents().get(0);
		private final Assignment cServiceThreadsAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cServiceThreadsThreadWithRoleParserRuleCall_4_1_0 = (RuleCall)cServiceThreadsAssignment_4_1.eContents().get(0);
		private final RuleCall cCOLONTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cPublicChannelAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final CrossReference cPublicChannelSiteCrossReference_6_0 = (CrossReference)cPublicChannelAssignment_6.eContents().get(0);
		private final RuleCall cPublicChannelSiteIDTerminalRuleCall_6_0_1 = (RuleCall)cPublicChannelSiteCrossReference_6_0.eContents().get(1);
		private final RuleCall cLPARENTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Assignment cSessionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSessionIDTerminalRuleCall_8_0 = (RuleCall)cSessionAssignment_8.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final RuleCall cSEMICOLONTerminalRuleCall_10_0 = (RuleCall)cGroup_10.eContents().get(0);
		private final Assignment cContinuationAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cContinuationChoreographyParserRuleCall_10_1_0 = (RuleCall)cContinuationAssignment_10_1.eContents().get(0);
		
		/// **
		// * Multiparty session start.
		// * Example: t1[role1],t2[role2] start t3[role3]: a(k)
		// * / Start: // List of active threads
		//	activeThreads+=ThreadWithRole (COMMA activeThreads+=ThreadWithRole)* "start" // List of service threads
		//	serviceThreads+=ThreadWithRole (COMMA serviceThreads+=ThreadWithRole)* COLON // Public channel name
		//	publicChannel=[Site] // Protocol name
		//	//LSQUARE protocol = ID RSQUARE
		//	// Private session name
		//	LPAREN session=ID RPAREN (SEMICOLON continuation=Choreography)?;
		public ParserRule getRule() { return rule; }

		//// List of active threads
		//activeThreads+=ThreadWithRole (COMMA activeThreads+=ThreadWithRole)* "start" // List of service threads
		//serviceThreads+=ThreadWithRole (COMMA serviceThreads+=ThreadWithRole)* COLON // Public channel name
		//publicChannel=[Site] // Protocol name
		////LSQUARE protocol = ID RSQUARE
		//// Private session name
		//LPAREN session=ID RPAREN (SEMICOLON continuation=Choreography)?
		public Group getGroup() { return cGroup; }

		//// List of active threads
		//activeThreads+=ThreadWithRole
		public Assignment getActiveThreadsAssignment_0() { return cActiveThreadsAssignment_0; }

		//ThreadWithRole
		public RuleCall getActiveThreadsThreadWithRoleParserRuleCall_0_0() { return cActiveThreadsThreadWithRoleParserRuleCall_0_0; }

		//(COMMA activeThreads+=ThreadWithRole)*
		public Group getGroup_1() { return cGroup_1; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_1_0() { return cCOMMATerminalRuleCall_1_0; }

		//activeThreads+=ThreadWithRole
		public Assignment getActiveThreadsAssignment_1_1() { return cActiveThreadsAssignment_1_1; }

		//ThreadWithRole
		public RuleCall getActiveThreadsThreadWithRoleParserRuleCall_1_1_0() { return cActiveThreadsThreadWithRoleParserRuleCall_1_1_0; }

		//"start"
		public Keyword getStartKeyword_2() { return cStartKeyword_2; }

		//// List of service threads
		//serviceThreads+=ThreadWithRole
		public Assignment getServiceThreadsAssignment_3() { return cServiceThreadsAssignment_3; }

		//ThreadWithRole
		public RuleCall getServiceThreadsThreadWithRoleParserRuleCall_3_0() { return cServiceThreadsThreadWithRoleParserRuleCall_3_0; }

		//(COMMA serviceThreads+=ThreadWithRole)*
		public Group getGroup_4() { return cGroup_4; }

		//COMMA
		public RuleCall getCOMMATerminalRuleCall_4_0() { return cCOMMATerminalRuleCall_4_0; }

		//serviceThreads+=ThreadWithRole
		public Assignment getServiceThreadsAssignment_4_1() { return cServiceThreadsAssignment_4_1; }

		//ThreadWithRole
		public RuleCall getServiceThreadsThreadWithRoleParserRuleCall_4_1_0() { return cServiceThreadsThreadWithRoleParserRuleCall_4_1_0; }

		//COLON
		public RuleCall getCOLONTerminalRuleCall_5() { return cCOLONTerminalRuleCall_5; }

		//// Public channel name
		//publicChannel=[Site]
		public Assignment getPublicChannelAssignment_6() { return cPublicChannelAssignment_6; }

		//[Site]
		public CrossReference getPublicChannelSiteCrossReference_6_0() { return cPublicChannelSiteCrossReference_6_0; }

		//ID
		public RuleCall getPublicChannelSiteIDTerminalRuleCall_6_0_1() { return cPublicChannelSiteIDTerminalRuleCall_6_0_1; }

		//// Protocol name
		////LSQUARE protocol = ID RSQUARE
		//// Private session name
		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_7() { return cLPARENTerminalRuleCall_7; }

		//session=ID
		public Assignment getSessionAssignment_8() { return cSessionAssignment_8; }

		//ID
		public RuleCall getSessionIDTerminalRuleCall_8_0() { return cSessionIDTerminalRuleCall_8_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_9() { return cRPARENTerminalRuleCall_9; }

		//(SEMICOLON continuation=Choreography)?
		public Group getGroup_10() { return cGroup_10; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_10_0() { return cSEMICOLONTerminalRuleCall_10_0; }

		//continuation=Choreography
		public Assignment getContinuationAssignment_10_1() { return cContinuationAssignment_10_1; }

		//Choreography
		public RuleCall getContinuationChoreographyParserRuleCall_10_1_0() { return cContinuationChoreographyParserRuleCall_10_1_0; }
	}

	public class ThreadWithRoleElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ThreadWithRole");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cThreadAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cThreadIDTerminalRuleCall_0_0 = (RuleCall)cThreadAssignment_0.eContents().get(0);
		private final RuleCall cLSQUARETerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cRoleAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRoleIDTerminalRuleCall_2_0 = (RuleCall)cRoleAssignment_2.eContents().get(0);
		private final RuleCall cRSQUARETerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		
		//// A thread with a role. Example: myThread[MyRole]
		//ThreadWithRole:
		//	thread=ID LSQUARE role=ID RSQUARE;
		public ParserRule getRule() { return rule; }

		//thread=ID LSQUARE role=ID RSQUARE
		public Group getGroup() { return cGroup; }

		//thread=ID
		public Assignment getThreadAssignment_0() { return cThreadAssignment_0; }

		//ID
		public RuleCall getThreadIDTerminalRuleCall_0_0() { return cThreadIDTerminalRuleCall_0_0; }

		//LSQUARE
		public RuleCall getLSQUARETerminalRuleCall_1() { return cLSQUARETerminalRuleCall_1; }

		//role=ID
		public Assignment getRoleAssignment_2() { return cRoleAssignment_2; }

		//ID
		public RuleCall getRoleIDTerminalRuleCall_2_0() { return cRoleIDTerminalRuleCall_2_0; }

		//RSQUARE
		public RuleCall getRSQUARETerminalRuleCall_3() { return cRSQUARETerminalRuleCall_3; }
	}

	public class InteractionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Interaction");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cSenderAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cSenderIDTerminalRuleCall_0_0 = (RuleCall)cSenderAssignment_0.eContents().get(0);
		private final Group cGroup_1 = (Group)cGroup.eContents().get(1);
		private final RuleCall cDOTTerminalRuleCall_1_0 = (RuleCall)cGroup_1.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cSenderExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cSenderExpressionExpressionParserRuleCall_1_2_0 = (RuleCall)cSenderExpressionAssignment_1_2.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_1_3 = (RuleCall)cGroup_1.eContents().get(3);
		private final RuleCall cARROWTerminalRuleCall_2 = (RuleCall)cGroup.eContents().get(2);
		private final Assignment cReceiverAssignment_3 = (Assignment)cGroup.eContents().get(3);
		private final RuleCall cReceiverIDTerminalRuleCall_3_0 = (RuleCall)cReceiverAssignment_3.eContents().get(0);
		private final Group cGroup_4 = (Group)cGroup.eContents().get(4);
		private final RuleCall cDOTTerminalRuleCall_4_0 = (RuleCall)cGroup_4.eContents().get(0);
		private final Assignment cReceiverVariableAssignment_4_1 = (Assignment)cGroup_4.eContents().get(1);
		private final RuleCall cReceiverVariableIDTerminalRuleCall_4_1_0 = (RuleCall)cReceiverVariableAssignment_4_1.eContents().get(0);
		private final RuleCall cCOLONTerminalRuleCall_5 = (RuleCall)cGroup.eContents().get(5);
		private final Assignment cOperationAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cOperationIDTerminalRuleCall_6_0 = (RuleCall)cOperationAssignment_6.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_7 = (RuleCall)cGroup.eContents().get(7);
		private final Assignment cSessionAssignment_8 = (Assignment)cGroup.eContents().get(8);
		private final RuleCall cSessionIDTerminalRuleCall_8_0 = (RuleCall)cSessionAssignment_8.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_9 = (RuleCall)cGroup.eContents().get(9);
		private final Group cGroup_10 = (Group)cGroup.eContents().get(10);
		private final RuleCall cSEMICOLONTerminalRuleCall_10_0 = (RuleCall)cGroup_10.eContents().get(0);
		private final Assignment cContinuationAssignment_10_1 = (Assignment)cGroup_10.eContents().get(1);
		private final RuleCall cContinuationChoreographyParserRuleCall_10_1_0 = (RuleCall)cContinuationAssignment_10_1.eContents().get(0);
		
		//// End of a choreography.
		////End: {End} 'end';
		/// ** 
		// * Interaction (data communication). Example: t1.(x + 2) -> t2.y : k
		// * 
		// * Comment: the syntax is not great now (parentheses around the expression are always
		// * present), but we will put some sugar on it in a later version. 
		// * / Interaction:
		//	sender= // The sender thread
		//	ID (DOT LPAREN senderExpression=Expression RPAREN)? // The expression whose evaluation has to be sent
		//	ARROW receiver= // The receiver thread
		//	ID (DOT receiverVariable=ID)? // The variable in which the receiver stores the received value
		//	COLON operation=ID LPAREN session= // The session of the interaction
		//	ID RPAREN (SEMICOLON continuation=Choreography)?;
		public ParserRule getRule() { return rule; }

		//sender= // The sender thread
		//ID (DOT LPAREN senderExpression=Expression RPAREN)? // The expression whose evaluation has to be sent
		//ARROW receiver= // The receiver thread
		//ID (DOT receiverVariable=ID)? // The variable in which the receiver stores the received value
		//COLON operation=ID LPAREN session= // The session of the interaction
		//ID RPAREN (SEMICOLON continuation=Choreography)?
		public Group getGroup() { return cGroup; }

		//sender= // The sender thread
		//ID
		public Assignment getSenderAssignment_0() { return cSenderAssignment_0; }

		//// The sender thread
		//ID
		public RuleCall getSenderIDTerminalRuleCall_0_0() { return cSenderIDTerminalRuleCall_0_0; }

		//(DOT LPAREN senderExpression=Expression RPAREN)?
		public Group getGroup_1() { return cGroup_1; }

		//DOT
		public RuleCall getDOTTerminalRuleCall_1_0() { return cDOTTerminalRuleCall_1_0; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1_1() { return cLPARENTerminalRuleCall_1_1; }

		//senderExpression=Expression
		public Assignment getSenderExpressionAssignment_1_2() { return cSenderExpressionAssignment_1_2; }

		//Expression
		public RuleCall getSenderExpressionExpressionParserRuleCall_1_2_0() { return cSenderExpressionExpressionParserRuleCall_1_2_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_1_3() { return cRPARENTerminalRuleCall_1_3; }

		//ARROW
		public RuleCall getARROWTerminalRuleCall_2() { return cARROWTerminalRuleCall_2; }

		//receiver= // The receiver thread
		//ID
		public Assignment getReceiverAssignment_3() { return cReceiverAssignment_3; }

		//// The receiver thread
		//ID
		public RuleCall getReceiverIDTerminalRuleCall_3_0() { return cReceiverIDTerminalRuleCall_3_0; }

		//(DOT receiverVariable=ID)?
		public Group getGroup_4() { return cGroup_4; }

		//DOT
		public RuleCall getDOTTerminalRuleCall_4_0() { return cDOTTerminalRuleCall_4_0; }

		//receiverVariable=ID
		public Assignment getReceiverVariableAssignment_4_1() { return cReceiverVariableAssignment_4_1; }

		//ID
		public RuleCall getReceiverVariableIDTerminalRuleCall_4_1_0() { return cReceiverVariableIDTerminalRuleCall_4_1_0; }

		//COLON
		public RuleCall getCOLONTerminalRuleCall_5() { return cCOLONTerminalRuleCall_5; }

		//operation=ID
		public Assignment getOperationAssignment_6() { return cOperationAssignment_6; }

		//ID
		public RuleCall getOperationIDTerminalRuleCall_6_0() { return cOperationIDTerminalRuleCall_6_0; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_7() { return cLPARENTerminalRuleCall_7; }

		//session= // The session of the interaction
		//ID
		public Assignment getSessionAssignment_8() { return cSessionAssignment_8; }

		//// The session of the interaction
		//ID
		public RuleCall getSessionIDTerminalRuleCall_8_0() { return cSessionIDTerminalRuleCall_8_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_9() { return cRPARENTerminalRuleCall_9; }

		//(SEMICOLON continuation=Choreography)?
		public Group getGroup_10() { return cGroup_10; }

		//SEMICOLON
		public RuleCall getSEMICOLONTerminalRuleCall_10_0() { return cSEMICOLONTerminalRuleCall_10_0; }

		//continuation=Choreography
		public Assignment getContinuationAssignment_10_1() { return cContinuationAssignment_10_1; }

		//Choreography
		public RuleCall getContinuationChoreographyParserRuleCall_10_1_0() { return cContinuationChoreographyParserRuleCall_10_1_0; }
	}

	public class IfThenElseElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "IfThenElse");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Keyword cIfKeyword_0 = (Keyword)cGroup.eContents().get(0);
		private final RuleCall cLPARENTerminalRuleCall_1 = (RuleCall)cGroup.eContents().get(1);
		private final Assignment cConditionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cConditionConditionParserRuleCall_2_0 = (RuleCall)cConditionAssignment_2.eContents().get(0);
		private final RuleCall cRPARENTerminalRuleCall_3 = (RuleCall)cGroup.eContents().get(3);
		private final RuleCall cATTerminalRuleCall_4 = (RuleCall)cGroup.eContents().get(4);
		private final Assignment cThreadAssignment_5 = (Assignment)cGroup.eContents().get(5);
		private final RuleCall cThreadIDTerminalRuleCall_5_0 = (RuleCall)cThreadAssignment_5.eContents().get(0);
		private final Assignment cThenAssignment_6 = (Assignment)cGroup.eContents().get(6);
		private final RuleCall cThenChoreographyParserRuleCall_6_0 = (RuleCall)cThenAssignment_6.eContents().get(0);
		private final Group cGroup_7 = (Group)cGroup.eContents().get(7);
		private final Keyword cElseKeyword_7_0 = (Keyword)cGroup_7.eContents().get(0);
		private final Assignment cElseAssignment_7_1 = (Assignment)cGroup_7.eContents().get(1);
		private final RuleCall cElseChoreographyParserRuleCall_7_1_0 = (RuleCall)cElseAssignment_7_1.eContents().get(0);
		
		/// **
		// * if (condition)@thread { Choreography } else { Choreography }
		// * / IfThenElse:
		//	"if" LPAREN condition=Condition RPAREN AT thread=ID then=Choreography ("else" else=Choreography)?;
		public ParserRule getRule() { return rule; }

		//"if" LPAREN condition=Condition RPAREN AT thread=ID then=Choreography ("else" else=Choreography)?
		public Group getGroup() { return cGroup; }

		//"if"
		public Keyword getIfKeyword_0() { return cIfKeyword_0; }

		//LPAREN
		public RuleCall getLPARENTerminalRuleCall_1() { return cLPARENTerminalRuleCall_1; }

		//condition=Condition
		public Assignment getConditionAssignment_2() { return cConditionAssignment_2; }

		//Condition
		public RuleCall getConditionConditionParserRuleCall_2_0() { return cConditionConditionParserRuleCall_2_0; }

		//RPAREN
		public RuleCall getRPARENTerminalRuleCall_3() { return cRPARENTerminalRuleCall_3; }

		//AT
		public RuleCall getATTerminalRuleCall_4() { return cATTerminalRuleCall_4; }

		//thread=ID
		public Assignment getThreadAssignment_5() { return cThreadAssignment_5; }

		//ID
		public RuleCall getThreadIDTerminalRuleCall_5_0() { return cThreadIDTerminalRuleCall_5_0; }

		//then=Choreography
		public Assignment getThenAssignment_6() { return cThenAssignment_6; }

		//Choreography
		public RuleCall getThenChoreographyParserRuleCall_6_0() { return cThenChoreographyParserRuleCall_6_0; }

		//("else" else=Choreography)?
		public Group getGroup_7() { return cGroup_7; }

		//"else"
		public Keyword getElseKeyword_7_0() { return cElseKeyword_7_0; }

		//else=Choreography
		public Assignment getElseAssignment_7_1() { return cElseAssignment_7_1; }

		//Choreography
		public RuleCall getElseChoreographyParserRuleCall_7_1_0() { return cElseChoreographyParserRuleCall_7_1_0; }
	}

	public class ExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Expression");
		private final Assignment cSumExpressionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cSumExpressionSumExpressionParserRuleCall_0 = (RuleCall)cSumExpressionAssignment.eContents().get(0);
		
		/// *** Expressions and conditions *** / Expression:
		//	sumExpression=SumExpression;
		public ParserRule getRule() { return rule; }

		//sumExpression=SumExpression
		public Assignment getSumExpressionAssignment() { return cSumExpressionAssignment; }

		//SumExpression
		public RuleCall getSumExpressionSumExpressionParserRuleCall_0() { return cSumExpressionSumExpressionParserRuleCall_0; }
	}

	public class SumExpressionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SumExpression");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cChildrenAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cChildrenExpressionBasicTermParserRuleCall_0_0 = (RuleCall)cChildrenAssignment_0.eContents().get(0);
		private final Assignment cChildrenAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cChildrenSumExpressionTermParserRuleCall_1_0 = (RuleCall)cChildrenAssignment_1.eContents().get(0);
		
		//SumExpression:
		//	children+=ExpressionBasicTerm children+=SumExpressionTerm*;
		public ParserRule getRule() { return rule; }

		//children+=ExpressionBasicTerm children+=SumExpressionTerm*
		public Group getGroup() { return cGroup; }

		//children+=ExpressionBasicTerm
		public Assignment getChildrenAssignment_0() { return cChildrenAssignment_0; }

		//ExpressionBasicTerm
		public RuleCall getChildrenExpressionBasicTermParserRuleCall_0_0() { return cChildrenExpressionBasicTermParserRuleCall_0_0; }

		//children+=SumExpressionTerm*
		public Assignment getChildrenAssignment_1() { return cChildrenAssignment_1; }

		//SumExpressionTerm
		public RuleCall getChildrenSumExpressionTermParserRuleCall_1_0() { return cChildrenSumExpressionTermParserRuleCall_1_0; }
	}

	public class SumExpressionTermElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "SumExpressionTerm");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Group cGroup_0 = (Group)cAlternatives.eContents().get(0);
		private final Action cSumExpressionAddTermAction_0_0 = (Action)cGroup_0.eContents().get(0);
		private final RuleCall cPLUSTerminalRuleCall_0_1 = (RuleCall)cGroup_0.eContents().get(1);
		private final Assignment cExpressionAssignment_0_2 = (Assignment)cGroup_0.eContents().get(2);
		private final RuleCall cExpressionExpressionBasicTermParserRuleCall_0_2_0 = (RuleCall)cExpressionAssignment_0_2.eContents().get(0);
		private final Group cGroup_1 = (Group)cAlternatives.eContents().get(1);
		private final Action cSumExpressionSubtractTermAction_1_0 = (Action)cGroup_1.eContents().get(0);
		private final RuleCall cMINUSTerminalRuleCall_1_1 = (RuleCall)cGroup_1.eContents().get(1);
		private final Assignment cExpressionAssignment_1_2 = (Assignment)cGroup_1.eContents().get(2);
		private final RuleCall cExpressionExpressionBasicTermParserRuleCall_1_2_0 = (RuleCall)cExpressionAssignment_1_2.eContents().get(0);
		
		//SumExpressionTerm:
		//	{SumExpressionAddTerm} PLUS expression=ExpressionBasicTerm | {SumExpressionSubtractTerm} MINUS
		//	expression=ExpressionBasicTerm;
		public ParserRule getRule() { return rule; }

		//{SumExpressionAddTerm} PLUS expression=ExpressionBasicTerm | {SumExpressionSubtractTerm} MINUS
		//expression=ExpressionBasicTerm
		public Alternatives getAlternatives() { return cAlternatives; }

		//{SumExpressionAddTerm} PLUS expression=ExpressionBasicTerm
		public Group getGroup_0() { return cGroup_0; }

		//{SumExpressionAddTerm}
		public Action getSumExpressionAddTermAction_0_0() { return cSumExpressionAddTermAction_0_0; }

		//PLUS
		public RuleCall getPLUSTerminalRuleCall_0_1() { return cPLUSTerminalRuleCall_0_1; }

		//expression=ExpressionBasicTerm
		public Assignment getExpressionAssignment_0_2() { return cExpressionAssignment_0_2; }

		//ExpressionBasicTerm
		public RuleCall getExpressionExpressionBasicTermParserRuleCall_0_2_0() { return cExpressionExpressionBasicTermParserRuleCall_0_2_0; }

		//{SumExpressionSubtractTerm} MINUS expression=ExpressionBasicTerm
		public Group getGroup_1() { return cGroup_1; }

		//{SumExpressionSubtractTerm}
		public Action getSumExpressionSubtractTermAction_1_0() { return cSumExpressionSubtractTermAction_1_0; }

		//MINUS
		public RuleCall getMINUSTerminalRuleCall_1_1() { return cMINUSTerminalRuleCall_1_1; }

		//expression=ExpressionBasicTerm
		public Assignment getExpressionAssignment_1_2() { return cExpressionAssignment_1_2; }

		//ExpressionBasicTerm
		public RuleCall getExpressionExpressionBasicTermParserRuleCall_1_2_0() { return cExpressionExpressionBasicTermParserRuleCall_1_2_0; }
	}

	public class ExpressionBasicTermElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ExpressionBasicTerm");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cVariableAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cVariableIDTerminalRuleCall_0_0 = (RuleCall)cVariableAssignment_0.eContents().get(0);
		private final Assignment cConstantAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cConstantConstantParserRuleCall_1_0 = (RuleCall)cConstantAssignment_1.eContents().get(0);
		
		//ExpressionBasicTerm:
		//	variable=ID | constant=Constant;
		public ParserRule getRule() { return rule; }

		//variable=ID | constant=Constant
		public Alternatives getAlternatives() { return cAlternatives; }

		//variable=ID
		public Assignment getVariableAssignment_0() { return cVariableAssignment_0; }

		//ID
		public RuleCall getVariableIDTerminalRuleCall_0_0() { return cVariableIDTerminalRuleCall_0_0; }

		//constant=Constant
		public Assignment getConstantAssignment_1() { return cConstantAssignment_1; }

		//Constant
		public RuleCall getConstantConstantParserRuleCall_1_0() { return cConstantConstantParserRuleCall_1_0; }
	}

	public class ConstantElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Constant");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final Assignment cIntValueAssignment_0 = (Assignment)cAlternatives.eContents().get(0);
		private final RuleCall cIntValueINTTerminalRuleCall_0_0 = (RuleCall)cIntValueAssignment_0.eContents().get(0);
		private final Assignment cStrValueAssignment_1 = (Assignment)cAlternatives.eContents().get(1);
		private final RuleCall cStrValueSTRINGTerminalRuleCall_1_0 = (RuleCall)cStrValueAssignment_1.eContents().get(0);
		
		//Constant:
		//	intValue=INT | strValue=STRING;
		public ParserRule getRule() { return rule; }

		//intValue=INT | strValue=STRING
		public Alternatives getAlternatives() { return cAlternatives; }

		//intValue=INT
		public Assignment getIntValueAssignment_0() { return cIntValueAssignment_0; }

		//INT
		public RuleCall getIntValueINTTerminalRuleCall_0_0() { return cIntValueINTTerminalRuleCall_0_0; }

		//strValue=STRING
		public Assignment getStrValueAssignment_1() { return cStrValueAssignment_1; }

		//STRING
		public RuleCall getStrValueSTRINGTerminalRuleCall_1_0() { return cStrValueSTRINGTerminalRuleCall_1_0; }
	}

	public class ConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "Condition");
		private final Assignment cCompareConditionAssignment = (Assignment)rule.eContents().get(1);
		private final RuleCall cCompareConditionCompareConditionParserRuleCall_0 = (RuleCall)cCompareConditionAssignment.eContents().get(0);
		
		//// Condition. Example: x < 5
		//Condition:
		//	compareCondition=CompareCondition;
		public ParserRule getRule() { return rule; }

		//compareCondition=CompareCondition
		public Assignment getCompareConditionAssignment() { return cCompareConditionAssignment; }

		//CompareCondition
		public RuleCall getCompareConditionCompareConditionParserRuleCall_0() { return cCompareConditionCompareConditionParserRuleCall_0; }
	}

	public class CompareConditionElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "CompareCondition");
		private final Group cGroup = (Group)rule.eContents().get(1);
		private final Assignment cLeftExpressionAssignment_0 = (Assignment)cGroup.eContents().get(0);
		private final RuleCall cLeftExpressionExpressionParserRuleCall_0_0 = (RuleCall)cLeftExpressionAssignment_0.eContents().get(0);
		private final Assignment cOperatorAssignment_1 = (Assignment)cGroup.eContents().get(1);
		private final RuleCall cOperatorConditionOperatorParserRuleCall_1_0 = (RuleCall)cOperatorAssignment_1.eContents().get(0);
		private final Assignment cRightExpressionAssignment_2 = (Assignment)cGroup.eContents().get(2);
		private final RuleCall cRightExpressionExpressionParserRuleCall_2_0 = (RuleCall)cRightExpressionAssignment_2.eContents().get(0);
		
		//CompareCondition:
		//	leftExpression=Expression operator=ConditionOperator rightExpression=Expression;
		public ParserRule getRule() { return rule; }

		//leftExpression=Expression operator=ConditionOperator rightExpression=Expression
		public Group getGroup() { return cGroup; }

		//leftExpression=Expression
		public Assignment getLeftExpressionAssignment_0() { return cLeftExpressionAssignment_0; }

		//Expression
		public RuleCall getLeftExpressionExpressionParserRuleCall_0_0() { return cLeftExpressionExpressionParserRuleCall_0_0; }

		//operator=ConditionOperator
		public Assignment getOperatorAssignment_1() { return cOperatorAssignment_1; }

		//ConditionOperator
		public RuleCall getOperatorConditionOperatorParserRuleCall_1_0() { return cOperatorConditionOperatorParserRuleCall_1_0; }

		//rightExpression=Expression
		public Assignment getRightExpressionAssignment_2() { return cRightExpressionAssignment_2; }

		//Expression
		public RuleCall getRightExpressionExpressionParserRuleCall_2_0() { return cRightExpressionExpressionParserRuleCall_2_0; }
	}

	public class ConditionOperatorElements extends AbstractParserRuleElementFinder {
		private final ParserRule rule = (ParserRule) GrammarUtil.findRuleForName(getGrammar(), "ConditionOperator");
		private final Alternatives cAlternatives = (Alternatives)rule.eContents().get(1);
		private final RuleCall cLESSTerminalRuleCall_0 = (RuleCall)cAlternatives.eContents().get(0);
		private final RuleCall cEQUALTerminalRuleCall_1 = (RuleCall)cAlternatives.eContents().get(1);
		private final RuleCall cGREATERTerminalRuleCall_2 = (RuleCall)cAlternatives.eContents().get(2);
		private final RuleCall cNOT_EQUALTerminalRuleCall_3 = (RuleCall)cAlternatives.eContents().get(3);
		
		//ConditionOperator:
		//	LESS | EQUAL | GREATER | NOT_EQUAL;
		public ParserRule getRule() { return rule; }

		//LESS | EQUAL | GREATER | NOT_EQUAL
		public Alternatives getAlternatives() { return cAlternatives; }

		//LESS
		public RuleCall getLESSTerminalRuleCall_0() { return cLESSTerminalRuleCall_0; }

		//EQUAL
		public RuleCall getEQUALTerminalRuleCall_1() { return cEQUALTerminalRuleCall_1; }

		//GREATER
		public RuleCall getGREATERTerminalRuleCall_2() { return cGREATERTerminalRuleCall_2; }

		//NOT_EQUAL
		public RuleCall getNOT_EQUALTerminalRuleCall_3() { return cNOT_EQUALTerminalRuleCall_3; }
	}
	
	
	private ProgramElements pProgram;
	private PreambleElements pPreamble;
	private ProtocolElements pProtocol;
	private SiteElements pSite;
	private GlobalTypeElements pGlobalType;
	private BranchGTypeElements pBranchGType;
	private DataTypeElements pDataType;
	private BasicTypeElements pBasicType;
	private LocalTypeElements pLocalType;
	private BranchTypeElements pBranchType;
	private ChoreographyElements pChoreography;
	private StartElements pStart;
	private ThreadWithRoleElements pThreadWithRole;
	private InteractionElements pInteraction;
	private IfThenElseElements pIfThenElse;
	private ExpressionElements pExpression;
	private SumExpressionElements pSumExpression;
	private SumExpressionTermElements pSumExpressionTerm;
	private ExpressionBasicTermElements pExpressionBasicTerm;
	private ConstantElements pConstant;
	private ConditionElements pCondition;
	private CompareConditionElements pCompareCondition;
	private ConditionOperatorElements pConditionOperator;
	private TerminalRule tLCURLY;
	private TerminalRule tRCURLY;
	private TerminalRule tLSQUARE;
	private TerminalRule tRSQUARE;
	private TerminalRule tARROW;
	private TerminalRule tSEMICOLON;
	private TerminalRule tCOLON;
	private TerminalRule tPLUS;
	private TerminalRule tTIMES;
	private TerminalRule tMINUS;
	private TerminalRule tVERT;
	private TerminalRule tQUESTION_MARK;
	private TerminalRule tBANG;
	private TerminalRule tAT;
	private TerminalRule tASSIGN;
	private TerminalRule tDOT;
	private TerminalRule tLPAREN;
	private TerminalRule tRPAREN;
	private TerminalRule tCOMMA;
	private TerminalRule tLESS;
	private TerminalRule tEQUAL;
	private TerminalRule tGREATER;
	private TerminalRule tNOT_EQUAL;
	
	private final GrammarProvider grammarProvider;

	private TerminalsGrammarAccess gaTerminals;

	@Inject
	public ChorGrammarAccess(GrammarProvider grammarProvider,
		TerminalsGrammarAccess gaTerminals) {
		this.grammarProvider = grammarProvider;
		this.gaTerminals = gaTerminals;
	}
	
	public Grammar getGrammar() {	
		return grammarProvider.getGrammar(this);
	}
	

	public TerminalsGrammarAccess getTerminalsGrammarAccess() {
		return gaTerminals;
	}

	
	//// Main nonterminal
	//Program:
	//	"program" name=ID SEMICOLON preamble=Preamble "main" LCURLY choreography=Choreography RCURLY;
	public ProgramElements getProgramAccess() {
		return (pProgram != null) ? pProgram : (pProgram = new ProgramElements());
	}
	
	public ParserRule getProgramRule() {
		return getProgramAccess().getRule();
	}

	//// Preamble of a program
	//Preamble:
	//	{Preamble} (protocols+=Protocol // Protocol definitions
	//	// Site definitions
	//	| site+=Site)*;
	public PreambleElements getPreambleAccess() {
		return (pPreamble != null) ? pPreamble : (pPreamble = new PreambleElements());
	}
	
	public ParserRule getPreambleRule() {
		return getPreambleAccess().getRule();
	}

	//// Definition of a protocol, associating a name to a multiparty behavioural type.
	//Protocol:
	//	"protocol" name=ID LCURLY type=GlobalType RCURLY;
	public ProtocolElements getProtocolAccess() {
		return (pProtocol != null) ? pProtocol : (pProtocol = new ProtocolElements());
	}
	
	public ParserRule getProtocolRule() {
		return getProtocolAccess().getRule();
	}

	//// Definition of a site, associating a public channel name to a protocol.
	//Site:
	//	"site" name=ID COLON protocol=[Protocol];
	public SiteElements getSiteAccess() {
		return (pSite != null) ? pSite : (pSite = new SiteElements());
	}
	
	public ParserRule getSiteRule() {
		return getSiteAccess().getRule();
	}

	//// Multiparty behavioural type, also denoted with G in comments for brevity (referring to the theoretical papers).
	//GlobalType: // Interaction. Example: A -> B: op(string); G
	//	sender=ID ARROW receiver=ID COLON (branches+=BranchGType | LCURLY branches+=BranchGType (COMMA branches+=BranchGType)*
	//	RCURLY);
	public GlobalTypeElements getGlobalTypeAccess() {
		return (pGlobalType != null) ? pGlobalType : (pGlobalType = new GlobalTypeElements());
	}
	
	public ParserRule getGlobalTypeRule() {
		return getGlobalTypeAccess().getRule();
	}

	//// Type of a branch. Example: label: G
	//BranchGType:
	//	operation=ID LPAREN dataType=DataType RPAREN (SEMICOLON continuation=GlobalType)?;
	public BranchGTypeElements getBranchGTypeAccess() {
		return (pBranchGType != null) ? pBranchGType : (pBranchGType = new BranchGTypeElements());
	}
	
	public ParserRule getBranchGTypeRule() {
		return getBranchGTypeAccess().getRule();
	}

	//// Data types. 
	//DataType:
	//	BasicType | LocalType;
	public DataTypeElements getDataTypeAccess() {
		return (pDataType != null) ? pDataType : (pDataType = new DataTypeElements());
	}
	
	public ParserRule getDataTypeRule() {
		return getDataTypeAccess().getRule();
	}

	//// Basic types. Example: int
	//BasicType:
	//	{BasicType} name="int" | name="string" | name="bool" | name="void";
	public BasicTypeElements getBasicTypeAccess() {
		return (pBasicType != null) ? pBasicType : (pBasicType = new BasicTypeElements());
	}
	
	public ParserRule getBasicTypeRule() {
		return getBasicTypeAccess().getRule();
	}

	//// Local types. 
	////	|
	//// End
	////	{EndType} 'end'
	//LocalType:
	//	{OutputType} BANG LPAREN datatype=DataType RPAREN SEMICOLON continuation=LocalType | {InputType} QUESTION_MARK LPAREN
	//	datatype=DataType RPAREN SEMICOLON continuation=LocalType | {BranchingType} QUESTION_MARK LCURLY branches+=BranchType
	//	(COMMA branches+=BranchType)* RCURLY | {SelectionType} BANG LCURLY branches+=BranchType (COMMA branches+=BranchType)*
	//	RCURLY;
	public LocalTypeElements getLocalTypeAccess() {
		return (pLocalType != null) ? pLocalType : (pLocalType = new LocalTypeElements());
	}
	
	public ParserRule getLocalTypeRule() {
		return getLocalTypeAccess().getRule();
	}

	//// Type of a branch. Example: label: L
	//BranchType:
	//	label=ID COLON LocalType;
	public BranchTypeElements getBranchTypeAccess() {
		return (pBranchType != null) ? pBranchType : (pBranchType = new BranchTypeElements());
	}
	
	public ParserRule getBranchTypeRule() {
		return getBranchTypeAccess().getRule();
	}

	/// **
	// * A choreography.
	// * TODO: introduce recursion
	// * / // | End
	//Choreography:
	//	Start | Interaction | IfThenElse | LCURLY Choreography RCURLY;
	public ChoreographyElements getChoreographyAccess() {
		return (pChoreography != null) ? pChoreography : (pChoreography = new ChoreographyElements());
	}
	
	public ParserRule getChoreographyRule() {
		return getChoreographyAccess().getRule();
	}

	/// **
	// * Multiparty session start.
	// * Example: t1[role1],t2[role2] start t3[role3]: a(k)
	// * / Start: // List of active threads
	//	activeThreads+=ThreadWithRole (COMMA activeThreads+=ThreadWithRole)* "start" // List of service threads
	//	serviceThreads+=ThreadWithRole (COMMA serviceThreads+=ThreadWithRole)* COLON // Public channel name
	//	publicChannel=[Site] // Protocol name
	//	//LSQUARE protocol = ID RSQUARE
	//	// Private session name
	//	LPAREN session=ID RPAREN (SEMICOLON continuation=Choreography)?;
	public StartElements getStartAccess() {
		return (pStart != null) ? pStart : (pStart = new StartElements());
	}
	
	public ParserRule getStartRule() {
		return getStartAccess().getRule();
	}

	//// A thread with a role. Example: myThread[MyRole]
	//ThreadWithRole:
	//	thread=ID LSQUARE role=ID RSQUARE;
	public ThreadWithRoleElements getThreadWithRoleAccess() {
		return (pThreadWithRole != null) ? pThreadWithRole : (pThreadWithRole = new ThreadWithRoleElements());
	}
	
	public ParserRule getThreadWithRoleRule() {
		return getThreadWithRoleAccess().getRule();
	}

	//// End of a choreography.
	////End: {End} 'end';
	/// ** 
	// * Interaction (data communication). Example: t1.(x + 2) -> t2.y : k
	// * 
	// * Comment: the syntax is not great now (parentheses around the expression are always
	// * present), but we will put some sugar on it in a later version. 
	// * / Interaction:
	//	sender= // The sender thread
	//	ID (DOT LPAREN senderExpression=Expression RPAREN)? // The expression whose evaluation has to be sent
	//	ARROW receiver= // The receiver thread
	//	ID (DOT receiverVariable=ID)? // The variable in which the receiver stores the received value
	//	COLON operation=ID LPAREN session= // The session of the interaction
	//	ID RPAREN (SEMICOLON continuation=Choreography)?;
	public InteractionElements getInteractionAccess() {
		return (pInteraction != null) ? pInteraction : (pInteraction = new InteractionElements());
	}
	
	public ParserRule getInteractionRule() {
		return getInteractionAccess().getRule();
	}

	/// **
	// * if (condition)@thread { Choreography } else { Choreography }
	// * / IfThenElse:
	//	"if" LPAREN condition=Condition RPAREN AT thread=ID then=Choreography ("else" else=Choreography)?;
	public IfThenElseElements getIfThenElseAccess() {
		return (pIfThenElse != null) ? pIfThenElse : (pIfThenElse = new IfThenElseElements());
	}
	
	public ParserRule getIfThenElseRule() {
		return getIfThenElseAccess().getRule();
	}

	/// *** Expressions and conditions *** / Expression:
	//	sumExpression=SumExpression;
	public ExpressionElements getExpressionAccess() {
		return (pExpression != null) ? pExpression : (pExpression = new ExpressionElements());
	}
	
	public ParserRule getExpressionRule() {
		return getExpressionAccess().getRule();
	}

	//SumExpression:
	//	children+=ExpressionBasicTerm children+=SumExpressionTerm*;
	public SumExpressionElements getSumExpressionAccess() {
		return (pSumExpression != null) ? pSumExpression : (pSumExpression = new SumExpressionElements());
	}
	
	public ParserRule getSumExpressionRule() {
		return getSumExpressionAccess().getRule();
	}

	//SumExpressionTerm:
	//	{SumExpressionAddTerm} PLUS expression=ExpressionBasicTerm | {SumExpressionSubtractTerm} MINUS
	//	expression=ExpressionBasicTerm;
	public SumExpressionTermElements getSumExpressionTermAccess() {
		return (pSumExpressionTerm != null) ? pSumExpressionTerm : (pSumExpressionTerm = new SumExpressionTermElements());
	}
	
	public ParserRule getSumExpressionTermRule() {
		return getSumExpressionTermAccess().getRule();
	}

	//ExpressionBasicTerm:
	//	variable=ID | constant=Constant;
	public ExpressionBasicTermElements getExpressionBasicTermAccess() {
		return (pExpressionBasicTerm != null) ? pExpressionBasicTerm : (pExpressionBasicTerm = new ExpressionBasicTermElements());
	}
	
	public ParserRule getExpressionBasicTermRule() {
		return getExpressionBasicTermAccess().getRule();
	}

	//Constant:
	//	intValue=INT | strValue=STRING;
	public ConstantElements getConstantAccess() {
		return (pConstant != null) ? pConstant : (pConstant = new ConstantElements());
	}
	
	public ParserRule getConstantRule() {
		return getConstantAccess().getRule();
	}

	//// Condition. Example: x < 5
	//Condition:
	//	compareCondition=CompareCondition;
	public ConditionElements getConditionAccess() {
		return (pCondition != null) ? pCondition : (pCondition = new ConditionElements());
	}
	
	public ParserRule getConditionRule() {
		return getConditionAccess().getRule();
	}

	//CompareCondition:
	//	leftExpression=Expression operator=ConditionOperator rightExpression=Expression;
	public CompareConditionElements getCompareConditionAccess() {
		return (pCompareCondition != null) ? pCompareCondition : (pCompareCondition = new CompareConditionElements());
	}
	
	public ParserRule getCompareConditionRule() {
		return getCompareConditionAccess().getRule();
	}

	//ConditionOperator:
	//	LESS | EQUAL | GREATER | NOT_EQUAL;
	public ConditionOperatorElements getConditionOperatorAccess() {
		return (pConditionOperator != null) ? pConditionOperator : (pConditionOperator = new ConditionOperatorElements());
	}
	
	public ParserRule getConditionOperatorRule() {
		return getConditionOperatorAccess().getRule();
	}

	//// Terminals
	//terminal LCURLY:
	//	"{";
	public TerminalRule getLCURLYRule() {
		return (tLCURLY != null) ? tLCURLY : (tLCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LCURLY"));
	} 

	//terminal RCURLY:
	//	"}";
	public TerminalRule getRCURLYRule() {
		return (tRCURLY != null) ? tRCURLY : (tRCURLY = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RCURLY"));
	} 

	//terminal LSQUARE:
	//	"[";
	public TerminalRule getLSQUARERule() {
		return (tLSQUARE != null) ? tLSQUARE : (tLSQUARE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LSQUARE"));
	} 

	//terminal RSQUARE:
	//	"]";
	public TerminalRule getRSQUARERule() {
		return (tRSQUARE != null) ? tRSQUARE : (tRSQUARE = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RSQUARE"));
	} 

	//terminal ARROW:
	//	"->";
	public TerminalRule getARROWRule() {
		return (tARROW != null) ? tARROW : (tARROW = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ARROW"));
	} 

	//terminal SEMICOLON:
	//	";";
	public TerminalRule getSEMICOLONRule() {
		return (tSEMICOLON != null) ? tSEMICOLON : (tSEMICOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "SEMICOLON"));
	} 

	//terminal COLON:
	//	":";
	public TerminalRule getCOLONRule() {
		return (tCOLON != null) ? tCOLON : (tCOLON = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COLON"));
	} 

	//terminal PLUS:
	//	"+";
	public TerminalRule getPLUSRule() {
		return (tPLUS != null) ? tPLUS : (tPLUS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "PLUS"));
	} 

	//terminal TIMES:
	//	"*";
	public TerminalRule getTIMESRule() {
		return (tTIMES != null) ? tTIMES : (tTIMES = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "TIMES"));
	} 

	//terminal MINUS:
	//	"-";
	public TerminalRule getMINUSRule() {
		return (tMINUS != null) ? tMINUS : (tMINUS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "MINUS"));
	} 

	//terminal VERT:
	//	"|";
	public TerminalRule getVERTRule() {
		return (tVERT != null) ? tVERT : (tVERT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "VERT"));
	} 

	//terminal QUESTION_MARK:
	//	"?";
	public TerminalRule getQUESTION_MARKRule() {
		return (tQUESTION_MARK != null) ? tQUESTION_MARK : (tQUESTION_MARK = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "QUESTION_MARK"));
	} 

	//terminal BANG:
	//	"!";
	public TerminalRule getBANGRule() {
		return (tBANG != null) ? tBANG : (tBANG = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "BANG"));
	} 

	//terminal AT:
	//	"@";
	public TerminalRule getATRule() {
		return (tAT != null) ? tAT : (tAT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "AT"));
	} 

	////terminal SESSIONDECL: 'session';
	////terminal STARTS: 'starts';
	////terminal ONE_WAY: 'OneWay';
	////terminal REQUEST_RESPONSE: 'RequestResponse';
	//terminal ASSIGN:
	//	"=";
	public TerminalRule getASSIGNRule() {
		return (tASSIGN != null) ? tASSIGN : (tASSIGN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "ASSIGN"));
	} 

	//terminal DOT:
	//	".";
	public TerminalRule getDOTRule() {
		return (tDOT != null) ? tDOT : (tDOT = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "DOT"));
	} 

	//terminal LPAREN:
	//	"(";
	public TerminalRule getLPARENRule() {
		return (tLPAREN != null) ? tLPAREN : (tLPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LPAREN"));
	} 

	//terminal RPAREN:
	//	")";
	public TerminalRule getRPARENRule() {
		return (tRPAREN != null) ? tRPAREN : (tRPAREN = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "RPAREN"));
	} 

	//terminal COMMA:
	//	",";
	public TerminalRule getCOMMARule() {
		return (tCOMMA != null) ? tCOMMA : (tCOMMA = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "COMMA"));
	} 

	//terminal LESS:
	//	"<";
	public TerminalRule getLESSRule() {
		return (tLESS != null) ? tLESS : (tLESS = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "LESS"));
	} 

	//terminal EQUAL:
	//	"==";
	public TerminalRule getEQUALRule() {
		return (tEQUAL != null) ? tEQUAL : (tEQUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "EQUAL"));
	} 

	//terminal GREATER:
	//	">";
	public TerminalRule getGREATERRule() {
		return (tGREATER != null) ? tGREATER : (tGREATER = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "GREATER"));
	} 

	//terminal NOT_EQUAL:
	//	"!=";
	public TerminalRule getNOT_EQUALRule() {
		return (tNOT_EQUAL != null) ? tNOT_EQUAL : (tNOT_EQUAL = (TerminalRule) GrammarUtil.findRuleForName(getGrammar(), "NOT_EQUAL"));
	} 

	//terminal ID:
	//	"^"? ("a".."z" | "A".."Z" | "_") ("a".."z" | "A".."Z" | "_" | "0".."9")*;
	public TerminalRule getIDRule() {
		return gaTerminals.getIDRule();
	} 

	//terminal INT returns ecore::EInt:
	//	"0".."9"+;
	public TerminalRule getINTRule() {
		return gaTerminals.getINTRule();
	} 

	//terminal STRING:
	//	"\"" ("\\" ("b" | "t" | "n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\""))* "\"" | "\'" ("\\" ("b" | "t" |
	//	"n" | "f" | "r" | "u" | "\"" | "\'" | "\\") | !("\\" | "\'"))* "\'";
	public TerminalRule getSTRINGRule() {
		return gaTerminals.getSTRINGRule();
	} 

	//terminal ML_COMMENT:
	//	"/ *"->"* /";
	public TerminalRule getML_COMMENTRule() {
		return gaTerminals.getML_COMMENTRule();
	} 

	//terminal SL_COMMENT:
	//	"//" !("\n" | "\r")* ("\r"? "\n")?;
	public TerminalRule getSL_COMMENTRule() {
		return gaTerminals.getSL_COMMENTRule();
	} 

	//terminal WS:
	//	(" " | "\t" | "\r" | "\n")+;
	public TerminalRule getWSRule() {
		return gaTerminals.getWSRule();
	} 

	//terminal ANY_OTHER:
	//	.;
	public TerminalRule getANY_OTHERRule() {
		return gaTerminals.getANY_OTHERRule();
	} 
}
