/*
* generated by Xtext
*/
package org.chor.ui.contentassist;

import org.chor.ui.contentassist.AbstractChorProposalProvider;
/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class ChorProposalProvider extends AbstractChorProposalProvider {

}
